import Head from 'next/head'
import dynamic from 'next/dynamic';
const AudioPlayer = dynamic(
  () => import('../src/components/AudioPlayer'),
  { ssr: false }
);
import  '../styles/Home.css';
import '../styles/style.less';

export default function Home() {
  return (
    <div className={'container'}>
      <Head>
        <title> SSBU Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'main'}>
        <h1 className={'title'}>
          Welcome to <a href="https://ssbu.edu.mm">SSBU Media!</a>
        </h1>
        <AudioPlayer />
      </main>

      <footer className={'footer'}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Make with ❤️{' '}  {' '}
          <span>
          By  SSBU IT Department
          </span>
        </a>
      </footer>
    </div>
  )
}
