import Head from 'next/head'

import Album from '../src/components/Album/Album';
import  '../styles/Home.css';
import '../styles/style.less';

export default function Home() {
  return (
    <div className={'container'}>
   
      <Head>
        <title> SSBU Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0,user-scalable=0"
        />
        <meta property="og:title" content={'SSBU Media'} />
        <meta property="og:site_name" content="Shan State Buddhist University | Media" />
        <meta property="og:type" content={'website'} />
        <meta property="og:url" content={'https://media.ssbu.edu.mm/'} />
        <meta
          property="og:image"
          content={
             'https://ssbu-media.sgp1.digitaloceanspaces.com/eng/ssbu-logo-preview.jpg'
             }
        />
        <meta property="og:image:alt" content={'Shan State Buddhist University Media'} />
        <meta property="og:description" content={"Shan State Buddhist University Media Team"} />
      </Head>
   <header>
    <nav> 
        <a href={'/'} className="logo">
         <img src={'https://ssbu-media.sgp1.digitaloceanspaces.com/media-ssbu.png'} />
         </a>  
     </nav>
   </header>
      <main className={'main'}>
      <Album />
    
      </main>

      <footer className={'footer'}>
        <a
          href="https://ssbu.edu.mm"
          target="_blank"
          rel="noopener noreferrer"
        >
          Make with ❤️{' '}  {' '}
          <span>
          By SSBU IT Department
          </span>
        </a>
      </footer>
    </div>
  )
}
